spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tutormsdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  database-platform: org.hibernate.dialect.MySQL5Dialect
  show-sql: true

message: have a great day - defaultS